# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# pip install pre-commit
# pre-commit install

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: no-commit-to-branch
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: debug-statements
        language_version: python3

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        files: ^src/
        args: []


